"""Add artisan payout accounts

Revision ID: 105cd1df3b35
Revises: 8aa0c0b9af9a
Create Date: 2026-08-09 09:47:06.509479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105cd1df3b35'
down_revision = '8aa0c0b9af9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=False),
    sa.Column('bank_code', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('recipient_code', sa.String(length=150), nullable=True),
    sa.Column('recipient_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_accounts_artisan_id'), ['artisan_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payout_accounts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_accounts_recipient_code'), ['recipient_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_accounts_recipient_code'))
        batch_op.drop_index(batch_op.f('ix_payout_accounts_is_active'))
        batch_op.drop_index(batch_op.f('ix_payout_accounts_artisan_id'))

    op.drop_table('payout_accounts')
    # ### end Alembic commands ###
