"""Add withdrawal audit trail

Revision ID: 18b75491ff14
Revises: 105cd1df3b35
Create Date: 2026-08-10 16:51:42.615591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b75491ff14'
down_revision = '105cd1df3b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('withdrawal_id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=30), server_default='system', nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_reference', sa.String(length=150), nullable=True),
    sa.Column('transfer_code', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['artisan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawal_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawal_audits_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_audits_artisan_id'), ['artisan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_audits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_audits_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_audits_provider_reference'), ['provider_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_audits_withdrawal_id'), ['withdrawal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawal_audits_withdrawal_id'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_audits_provider_reference'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_audits_event_type'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_audits_created_at'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_audits_artisan_id'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_audits_actor_user_id'))

    op.drop_table('withdrawal_audits')
    # ### end Alembic commands ###
