"""Add wallets transactions and withdrawals

Revision ID: 8aa0c0b9af9a
Revises: 2677857a693f
Create Date: 2026-08-07 13:07:45.046310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa0c0b9af9a'
down_revision = '2677857a693f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('available_balance', sa.Float(), nullable=False),
    sa.Column('pending_balance', sa.Float(), nullable=False),
    sa.Column('total_earned', sa.Float(), nullable=False),
    sa.Column('total_withdrawn', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=True)

    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('recipient_code', sa.String(length=150), nullable=True),
    sa.Column('transfer_code', sa.String(length=150), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['artisan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_code')
    )
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawals_approved_by'), ['approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawals_artisan_id'), ['artisan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawals_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_withdrawals_status'), ['status'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_reference', sa.String(length=150), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('artisan_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('artisan_id', sa.Integer(), nullable=True),
    sa.Column('service_request_id', sa.Integer(), nullable=True),
    sa.Column('withdrawal_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_artisan_id'), ['artisan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_provider_reference'), ['provider_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_service_request_id'), ['service_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_withdrawal_id'), ['withdrawal_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_withdrawal_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_service_request_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_transactions_provider_reference'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_artisan_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawals_status'))
        batch_op.drop_index(batch_op.f('ix_withdrawals_reference'))
        batch_op.drop_index(batch_op.f('ix_withdrawals_artisan_id'))
        batch_op.drop_index(batch_op.f('ix_withdrawals_approved_by'))

    op.drop_table('withdrawals')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))

    op.drop_table('wallets')
    # ### end Alembic commands ###
